apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: main-api-metrics
  namespace: monitoring
  labels:
    app: main-api
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: main-api
  namespaceSelector:
    matchNames:
    - main-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
