apiVersion: v1
kind: ConfigMap
metadata:
  name: main-api-config
  namespace: main-api
  labels:
    app: main-api
    project: aws-challenge
data:
  APP_VERSION: "1.0.4"
  ENVIRONMENT: "development"
  LOG_LEVEL: "INFO"
  DEBUG: "false"
  AUXILIARY_SERVICE_URL: "http://auxiliary-service.auxiliary-service.svc.cluster.local:8001"
