apiVersion: v1
kind: Service
metadata:
  name: auxiliary-service
  namespace: auxiliary-service
  labels:
    app: auxiliary-service
    project: aws-challenge
spec:
  type: ClusterIP
  selector:
    app: auxiliary-service
  ports:
  - name: http
    port: 8001
    targetPort: 8001
    protocol: TCP
  sessionAffinity: None
